### ISSUE TITLE
General - Inner Pages: Body background color doesn't matched from the given design which resulted to the background image in the right doesn't look good and seems like it is cut off

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Emu-Plains-Quality-Dry-Cleaning#13]
![image](https://cloud.githubusercontent.com/assets/13363508/13517587/a68fbfa0-e1ff-11e5-8c9d-684311cd5647.png)

**Comment by maehtitan** [comment]
Still not achieved

**Comment by maehtitan** [comment]
![image](https://cloud.githubusercontent.com/assets/13363508/13940290/110eb3d4-f017-11e5-8691-b4889aa635c1.png)

**Comment by maehtitan** [comment]
Too far from being fixed please look closely the background in the psd template

**Comment by maehtitan** [comment]
Yes, the gray filter is already applied but it is still not achieve from the design. Too far from being fixed please look closely the background in the psd template which blends with the image
![image](https://cloud.githubusercontent.com/assets/13363508/14129879/bd75ff2a-f660-11e5-85b2-df7534fc77cd.png)

**Comment by asif-titan** [comment]
Please Check again.
Thanks.

**Comment by maehtitan** [comment]
@asif-titan the blur so annoying it doesn't blend just like the left side of the image
![image](https://cloud.githubusercontent.com/assets/13363508/14130209/05df6d52-f664-11e5-81b9-47f2ae1f40c3.png)

**Comment by maehtitan** [comment]
Current fixed, it really not matched from the design, please update the content-bg class to adjust the blur to 4 and add to opacity to .5
![image](https://cloud.githubusercontent.com/assets/13363508/14135702/964c533c-f691-11e5-8080-01937a1042ea.png)

Please match the background wrapper to above background color to #f9f9f9 and please apply the webkit fix in chrome coz it doesn't reflected
![image](https://cloud.githubusercontent.com/assets/13363508/14135761/ee6d1b1e-f691-11e5-8a79-38037d19bb6e.png)
