### ISSUE TITLE
General: Header background layout exceeded from the 1140px area

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Emu-Plains-Quality-Dry-Cleaning#3]
![image](https://cloud.githubusercontent.com/assets/13363508/13516093/f034a958-e1f1-11e5-80b8-e926c6ef8fbe.png)

**Comment by asif-titan** [comment]
As per the design the container is 1170px wide,
![content-width](https://cloud.githubusercontent.com/assets/13450796/13626851/97e921fe-e5eb-11e5-96b2-0f2c6a1ab555.png)

**Comment by maehtitan** [comment]
@asif-titan,  

This is not invalid, yes 1170px is the actual design grid but it in 1140px area where all the contents resided because of the gutter which is 30px. Have you noticed that all of the elements on the right side are aligned based from the given design? 

![image](https://cloud.githubusercontent.com/assets/13363508/13662278/4217612a-e6d4-11e5-813f-9ff6b388ba2f.png)

Removing the top menu class will make it fix,
![image](https://cloud.githubusercontent.com/assets/13363508/13662231/fe7ddc64-e6d3-11e5-899f-72aefcf6bcfb.png)

**Comment by maehtitan** [comment]
Sorry but after clearing the cache hard still no changes has been found
![image](https://cloud.githubusercontent.com/assets/13363508/13940117/9e589e8c-f015-11e5-8a51-69fb93d77a7a.png)

**Comment by asif-titan** [comment]
Please check now
 i had to update the changes in dev-adm
