### ISSUE TITLE
Testimonials:  NEVER use ShortenText() as per standard KB link here https://knowledgebase.titanweb.com.au/implementation/standard-pages/post-title-and-post-desription

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Emu-Plains-Quality-Dry-Cleaning#36]
![image](https://cloud.githubusercontent.com/assets/13363508/13523412/4ce9d37e-e230-11e5-9fec-a6ed429dc7ef.png)

**Comment by asif-titan** [comment]
That is not Shortened text but the dots and quotes are hard coded as per the design.

**Comment by maehtitan** [comment]
Only mentioned in the scope to enclosed in quotes and not included the elipses (...)
![image](https://cloud.githubusercontent.com/assets/13363508/13662509/012c83b4-e6d6-11e5-81f9-ceb59d50a04b.png)
