### ISSUE TITLE
Homepage - Content Area and About Us page: Yes, the "View More" and "View Less" already implemented but the content shown is too short

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Emu-Plains-Quality-Dry-Cleaning#49]
![image](https://cloud.githubusercontent.com/assets/13363508/13665772/fed592c8-e6e8-11e5-8751-086ed6de660b.png)
![image](https://cloud.githubusercontent.com/assets/13363508/13691075/c289dce2-e770-11e5-86d3-200a230d2325.png)

**Comment by asif-titan** [comment]
The view more view less functionality works by the number of HTML elements (tags) given, as per the design the view more is shown after three elements, you are adding three single line paragraphs while testing so it is showing only three lines, please add paragraphs with more lines and check,

**Comment by maehtitan** [comment]
Hi @asif-titan 

This is not invalid. The issue here is you started the content at the middle where based from the given design (see below screenshot) it should start right after 64px height of space gap
![image](https://cloud.githubusercontent.com/assets/13363508/13939611/6b085d96-f011-11e5-97c0-b4324364f857.png)

And the contents should cater to 16 lines of text including the empty lines. 

View more button should start right after 45px
![image](https://cloud.githubusercontent.com/assets/13363508/13939648/cf594242-f011-11e5-9c3f-33550ad77e97.png)

And the bottom space should be 35px while currently still too high 
![image](https://cloud.githubusercontent.com/assets/13363508/13939662/f5c63034-f011-11e5-8fdc-63766e601838.png)

Hope it makes sense.

Thanks

**Comment by maehtitan** [comment]
on the first screenshot on the comment above is fixed the rest still not achieved

**Comment by asif-titan** [comment]
Hi Maeh, The read more / less functionality does not work on number of lines instead it works on the number of HTML Elements given, as per the design There are 3 paragraphs shown before read more, so i have set the script to show 3 HTML elements before read more, the content you have added has three one line paragraphs that is the reason it is showing only three lines, if you add Three Paragraphs of 10 lines each it will show 33 lines on content including the space between the paragraphs.
Please check with Roselie or Bernard regarding this.
