### ISSUE TITLE
General: Unable to update logo

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Emu-Plains-Quality-Dry-Cleaning#60]
![image](https://cloud.githubusercontent.com/assets/13363508/13941458/bc804a1a-f022-11e5-8f6e-5b67c1b14775.png)

**Comment by maehtitan** [comment]
Please implement it correctly coz when removing the logo and clicking save or changing to other image it will still show the logo which is the site logo again

**Comment by asif-titan** [comment]
Please check under header group in Titan Theme options page.
