### ISSUE TITLE
News: Infinite scrolling is not implemented as per project scope.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Emu-Plains-Quality-Dry-Cleaning#9]
![image](https://cloud.githubusercontent.com/assets/13363508/13520345/87b40f9e-e21a-11e5-8d62-9447e3a99456.png)

**Comment by maehtitan** [comment]
Where is the fix from this? I can't see the infinite looping as per project scope mentioned and the design shown?

**Comment by asif-titan** [comment]
Please Check again.
